microsoft/computervision-recipes

CONTRIBUTING.md
Removed references to recommender in our contrib.
=> Remove references to recommender in contribution.md

.ci/templates/unit-test-steps.yml
=> Remove conda env in case it was not created correctl

.gitignore, MANIFEST.in, README.md, environment.yml, setup.py, utils_cv/README.md, utils_cv/__init__.py
=> Make utils_cv pip-installable

.ci/azure-pipeline-azureml-notebook-test.yml
=> azureml-notebook-test-linux-cpu to only trigger every night

contrib/README.md
Adding a contrib folder for external contributions.
=> Added contrib folder

detection/notebooks/11_exploring_hyperparameters_on_azureml.ipynb
=> OD hyperdrive notebook

tests/conftest.py, tests/unit/classification/test_classification_notebooks.py, tests/unit/similarity/test_similarity_model.py, utils_cv/classification/model.py, utils_cv/common/data.py
bug fixes in pytest unit tests
=> cleanup and fix unit tests

classification/notebooks/01_training_introduction.ipynb, classification/notebooks/02_multilabel_classification.ipynb, detection/notebooks/11_exploring_hyperparameters_on_azureml.ipynb, environment.yml
running into this `AttributeError: module 'torch' has no attribute 'gesv'` issue which requires upgrading fastai to 1.0.57 (https://forums.fast.ai/t/fastai-pytorch-import-error/52201/2)
=> pytest fixes

README.md
now that we're working on detection, clearly show scenarios at top of readme
=> Update README.md for object detection

environment.yml
Merging environment.yaml file from staging into master. 
Am testing atm if with this change also the windows CPU devops test will run successfully.
=> Updating environment.yml file in master

environment.yml
Removed duplicate library from environment.yaml file.
=> removed duplicate cython

utils_cv/detection/dataset.py
Fixed a bug I introduced which is triggered when some of the images do not have any annotated bounding boxes in them.
=> Fix bug in reading VOC files

README.md
Our landing page was not explaining very clearly on why we need computer vision best practices repo is needed. So I have added a paragraph on that, also added a paragraph to overview section . I still think that we need to change our directory structure by creating a separate folder for "scenario" or "examples" that will host 3 various folders for all classification, detection, similarity. Each folder will contain specific notebooks example. This will enable us to have one link to go to all notebooks that we can add us hyperlink on our landing page, similarly we can do with one hyper link for Utility Functions. Also I think we should move our "set up" instruction to a separate set up page . These changes will enable our landing page to be really crisp on value proposition, overview and …
=> Anupams updating readme file

.ci/azure-pipeline-linux-cpu.yml, .ci/azure-pipeline-linux-gpu.yml, .ci/azure-pipeline-windows-cpu.yml, .ci/azure-pipeline-windows-gpu.yml
Update agents (in the new Azure subscriptions) for running the build pipeline
=> Update YAML files for Azure Pipelines

utils_cv/detection/plot.py
=> fix col=1 error for plot_grid

.ci/AML-nightly-gpu.yml
Adding more time to the run, after discussing with @PatrickBue, it looks that the best option is to merge this into master and then merge master with staging. Then everything should be synchronized and you (hopefully) shouldn't get conflicts when merging all the changes you have in staging to master
=> update maximum time

environment.yml
=> env-update

contrib/action_recognition/README.md
Add an Action Recognition example gif
=> Add example gif to action recognition readme

tests/.ci/azure-pipeline-windows-cpu.yml, tests/.ci/azure-pipeline-windows-gpu.yml, tests/integration/similarity/test_integration_similarity_notebooks.py, tests/unit/detection/test_detection_notebooks.py
=> windows testing fix and other testing bugs

SETUP.md, contrib/vm_builder/README.md
redo-ing this PR
broken link in setup: #412 #397 #394
vm_builder doesn't work on windows: #391
guidance on vm size and windows/linux: #392
=> fixes from bugbash

contrib/README.md
=> Update README.md in master

tests/.ci/azure-pipeline-windows-cpu.yml, tests/.ci/azure-pipeline-windows-gpu.yml
I had a similar error in reco https://github.com/microsoft/recommenders/pull/985, right now your pipeline is not failing because you have `continueOnError` skip the error when the folder `cv` does not exist, however, the current pipeline won't detect if there is a different error. This change just check whether there is a folder called `cv` and then erase it
=> if folder exists, remove

README.md
Replaced Marketing links with relevant Docs pages, which are more useful to the Github audience.
=> Link to relevant Docs pages for Azure services

tests/unit/detection/test_detection_notebooks.py, utils_cv/detection/data.py
Tune the keypoint model with only 2 keypoints for all categories in the dataset.
=> Add keypoint detection model tuning with top and bottom keypoints

NOTICE.txt
=> Add NOTICE file.

utils_cv/detection/plot.py
Plot keypoints as round dots to make them noticeable.
=> Plot keypoints as round dots to make them noticeable

utils_cv/detection/mask.py
Simplify `utils_cv.detection.mask.binarise_mask()`.
=> Simplify binarise_mask()

contrib/action_recognition/i3d/test.py
remove leftover conflict code #468
=> i3d test fix

scenarios/detection/README.md
=> update detection readme to fix broken link

tests/.ci/run_pytest.py, tests/integration/detection/test_integration_detection.py
Show how long each test takes to run
=> show test durations

.github/PULL_REQUEST_TEMPLATE.md
We need to update the pull request template for squashing merging commits in a pull request as a single commit into `staging` to maintain a clear and concise git history of the branch.
=> Update pull request template for squash merging into staging

scenarios/README.md
as requested, submitting the pr to the staging branch
=> fix broken link

README.md
Add more figures to root readme.
=> Small readme beautification

contrib/README.md, contrib/vmss_builder/README.md, contrib/vmss_builder/vm_user_env_setup.sh, contrib/vmss_builder/vmss_deploy_with_public_ip.py
=> vmss setup

environment.yml
Pinned the version of Python to 3.7.6 to meet AzureML requirements as it requires pinning Python to a specific version.
=> Fix AzureML tests

contrib/README.md, contrib/vmss_builder/README.md, contrib/vmss_builder/vm_user_env_setup.sh, contrib/vmss_builder/vmss_deploy_with_public_ip.py, environment.yml
Syncing staging <> master branches to fix the unit tests for master.
=> Syncing staging <> master branches

utils_cv/detection/references/README.txt, utils_cv/detection/references/coco_eval.py, utils_cv/detection/references/coco_utils.py, utils_cv/detection/references/engine.py, utils_cv/detection/references/group_by_aspect_ratio.py, utils_cv/detection/references/train.py, utils_cv/detection/references/transforms.py, utils_cv/detection/references/utils.py
Updating the references files for object detection with torchvision's newest version. Only had to do two minor edits to the original files:
- change from "import X" to "from . import X"
- add return statement in one function.
=> Update OD reference files

README.md
Adding status update to root readme.
- [n/a] I have added tests covering my contributions.
=> Create release annoucement

AUTHORS.md, CONTRIBUTING.md, SETUP.md
Updating mainly the setup instructions
- [n/a] I have added tests covering my contributions.
=> Readme updates

README.md, scenarios/tracking/README.md
Small updates to two readmes.
- [n/a] This PR is being made to `staging` and not `master`
- [n/a] I will squash merge this PR into `staging`
=> Small edits to readmes (#573)

scenarios/tracking/FAQ.md, scenarios/tracking/README.md
- [x ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [NA ] I have added tests covering my contributions.
- [x ] I have updated the documentation accordingly.
- [x ] This PR is being made to `staging` and not `master`
- [x ] I will squash merge this PR into `staging`
=> Lorenzov readme

scenarios/tracking/README.md
Adding setup instructions for the tracking scenario
=> Tracking setup instructions

scenarios/tracking/02_mot_challenge.ipynb
=> rewording markdown

utils_cv/tracking/data.py, utils_cv/tracking/dataset.py
Changing to use VOC input for training. 
THIS IS WORK IN PROGRESS
=> Use VOC format for training

tests/.ci/submit_azureml_pytest.py
Sync master <-> staging
- [n/a] This PR is being made to `staging` and not `master`
- [n/a] I will squash merge this PR into `staging`
=> Sync master <-> staging

utils_cv/action_recognition/model.py
Fix format bug of path string.
Failed to save checkpoints while training the model using `video_learner.fit(save_model=True)`.
None
=> [fix] failed to save checkpoints in VideoLearner.fit()

contrib/html_demo/JupyterCode/3_deployment_to_azure_app_service.ipynb, contrib/html_demo/UICode/index.html, contrib/html_demo/UICode/script.js, scenarios/action_recognition/00_webcam.ipynb, scenarios/action_recognition/10_video_transformation.ipynb, scenarios/classification/00_webcam.ipynb, scenarios/classification/01_training_introduction.ipynb, scenarios/classification/23_aci_aks_web_service_testing.ipynb, scenarios/classification/25_deployment_on_azure_apps_service_and_setting_CORS_policies.ipynb, scenarios/detection/00_webcam.ipynb, scenarios/detection/02_mask_rcnn.ipynb, scenarios/detection/03_keypoint_rcnn.ipynb, scenarios/segmentation/01_training_introduction.ipynb, tests/conftest.py, tests/unit/classification/test_classification_model.py, tests/unit/detection/test_detection_data.py, utils_cv/action_recognition/data.py, utils_cv/classification/data.py, utils_cv/detection/data.py, utils_cv/detection/model.py, utils_cv/segmentation/data.py, utils_cv/similarity/data.py, utils_cv/tracking/data.py
Changing location of assets to different url.
- [n/a] I have added tests covering my contributions.
- [n/a] I have updated the documentation accordingly.
=> Update assets location

utils_cv/classification/data.py, utils_cv/classification/parameter_sweeper.py
=> Missing `f` prefix on f-strings fix
